fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: [--maxkb=5000]
    -   id: debug-statements
    -   id: check-shebang-scripts-are-executable
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: []

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910-1
#    hooks:
#    -   id: mypy
#        files: ^utils/
#        args: []
