language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/rafelafrance/stacked_regex.git@master#egg=stackedregex
script:
  - python -m unittest discover
