language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/rafelafrance/stacked-regex.git#egg=stackedregex
script:
  - python -m unittest discover
